a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('É alfabético?: ', a.isalpha())
print('É numérico?: ', a.isnumeric())
print('É alfanumérico?: ', a.isalnum())
print('Só tem espaços?: ', a.isspace())
print('É tudo maiúsculo?: ', a.isupper())
print('É tudo minúsuclo?: ', a.islower())
print('É capitalizado?: ', a.istitle())
